# Generated by Django 4.1 on 2022-10-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_objetoventa_delete_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoventa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
