# Generated by Django 4.1 on 2022-10-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_objetoventa_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objetoventa',
            old_name='nombre',
            new_name='objeto',
        ),
        migrations.AlterField(
            model_name='objetoventa',
            name='vendedor',
            field=models.CharField(max_length=60),
        ),
    ]
