# Generated by Django 4.1 on 2022-10-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_objetoventa_precio_alter_objetoventa_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoventa',
            name='apellido',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='objetoventa',
            name='contacto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objetoventa',
            name='nombre',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
